# Generated by Django 3.1.1 on 2021-02-16 22:07

from django.db import migrations
from django.core.management import call_command


def load_init_data(apps, schema_editor):
    call_command("loaddata", "filterapp/fixtures/domain.json")
    call_command("loaddata", "filterapp/fixtures/domain_category.json")
    call_command("loaddata", "filterapp/fixtures/institution.json")
    call_command("loaddata", "filterapp/fixtures/code.json")


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_init_data),
    ]
