# Generated by Django 3.1.7 on 2021-04-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0003_auto_20210402_2012'),
    ]

    operations = [
        migrations.RunSQL("update filterapp_domain_category set category_name='renal failure' where category_name='renal Failure' and domain_id=5;"),
        migrations.RunSQL("update filterapp_domain_category set category_name='low socioeconomic status' where category_name='low' and domain_id=8;"),
        migrations.RunSQL("update filterapp_domain_category set category_name='medium socioeconomic status' where category_name='medium' and domain_id=8;"),
        migrations.RunSQL("update filterapp_domain_category set category_name='high socioeconomic status' where category_name='high' and domain_id=8;"),
        migrations.RunSQL("update filterapp_patient set domain5='renal failure' where domain5='renal Failure'"),
        migrations.RunSQL("update filterapp_patient set domain8='low socioeconomic status' where domain8='low'"),
        migrations.RunSQL("update filterapp_patient set domain8='medium socioeconomic status' where domain8='medium'"),
        migrations.RunSQL("update filterapp_patient set domain8='high socioeconomic status' where domain8='high'"),
    ]
