STATUS_PHASE_I = "PHASE I"
STATUS_PHASE_II = "PHASE II"
STATUS_PHASE_III = "PHASE III"
STATUS_PHASE_EXTRA = 'PHASE EXTRA'
STATUS_EXISTING = "EXISTING"
STATUS_INIT = 'INIT'
STATUS_ACTIVE = 'ACTIVE'
STATUS_INACTIVE = 'INACTIVE'
ELO_DEFAULT_RANKING = 1200
K_FACTOR = 23
NO_OF_DOMAINS = 9

